name: kaon_sa_kuan
description: Kaon sa Kuan food decision app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^6.3.0
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.20.2
  http: ^1.6.0
  image_picker: ^1.2.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/og.png
    - assets/images/dummy ahh.png
    - assets/images/shesh.png
    - assets/images/thinking 1.png
    - assets/images/thinking 2.png
    - assets/images/yum.png
  fonts:
    - family: AdlamDisplay
      fonts:
        - asset: assets/fonts/ADLaMDisplay-Regular.ttf
    - family: Afacad
      fonts:
        - asset: assets/fonts/Afacad-VariableFont_wght.ttf
